"""Document-type registry: loads templates/registry/*.json (generated by
scripts/generate_registry.py) and provides the generic field model, prompt,
and validation machinery the chat endpoint uses for every document type,
Mutual NDA included.

Fields are typed loosely (text/date/integer/list/enum/party) rather than with
a bespoke Pydantic class per document type, since the free-tier LLM's output
is validated field-by-field on the way out regardless (see validate_fields) -
the same "never trust the LLM wholesale" posture chat.py already used for NDA.
"""

import json
import re
from typing import Any, Literal

from pydantic import BaseModel

from app.settings import settings

FieldType = Literal["text", "date", "integer", "list", "enum", "party"]

DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")
MIN_EFFECTIVE_DATE_YEAR = 1900
MIN_INTEGER_VALUE = 1
MAX_INTEGER_VALUE = 99


class PartyFields(BaseModel):
    companyName: str | None = None
    signerName: str | None = None
    signerTitle: str | None = None
    noticeAddress: str | None = None


class FieldSpec(BaseModel):
    id: str
    label: str
    type: FieldType
    required: bool = False
    options: tuple[str, ...] | None = None
    promptHint: str | None = None


class DocumentTypeDescriptor(BaseModel):
    id: str
    catalogNames: tuple[str, ...]
    templateFiles: tuple[str, ...]
    fields: tuple[FieldSpec, ...]


def _load_registry() -> dict[str, DocumentTypeDescriptor]:
    registry: dict[str, DocumentTypeDescriptor] = {}
    registry_dir = settings.templates_dir / "registry"
    for path in sorted(registry_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        descriptor = DocumentTypeDescriptor(**data)
        registry[descriptor.id] = descriptor
    return registry


REGISTRY: dict[str, DocumentTypeDescriptor] = _load_registry()


def catalog_summary() -> str:
    """Formats every registered document type's name(s)/description for the
    classification-turn system prompt."""
    lines = []
    for descriptor in REGISTRY.values():
        lines.append(f"- {descriptor.id}: {' / '.join(descriptor.catalogNames)}")
    return "\n".join(lines)


# --- field validation (mirrors chat.py's original per-field validators,
# generalized to be dispatched by FieldSpec.type instead of hardcoded) -------


def _valid_party(raw: object) -> PartyFields | None:
    if not isinstance(raw, dict):
        return None
    cleaned = {
        key: value.strip()
        for key, value in raw.items()
        if key in PartyFields.model_fields and isinstance(value, str) and value.strip()
    }
    return PartyFields(**cleaned) if cleaned else None


def _valid_text(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _valid_date(value: object) -> str | None:
    if not isinstance(value, str) or not DATE_PATTERN.match(value):
        return None
    if int(value[:4]) < MIN_EFFECTIVE_DATE_YEAR:
        return None
    return value


def _valid_integer(value: object) -> int | None:
    if not isinstance(value, int) or isinstance(value, bool):
        return None
    return value if MIN_INTEGER_VALUE <= value <= MAX_INTEGER_VALUE else None


def _valid_list(value: object) -> list[str] | None:
    if not isinstance(value, list):
        return None
    cleaned = [item.strip() for item in value if isinstance(item, str) and item.strip()]
    return cleaned or None


def _valid_enum(value: object, options: tuple[str, ...] | None) -> str | None:
    return value if options and value in options else None


def _validate_one(field: FieldSpec, value: object) -> object | None:
    if field.type == "party":
        result = _valid_party(value)
        return result.model_dump(exclude_none=True) if result else None
    if field.type == "date":
        return _valid_date(value)
    if field.type == "integer":
        return _valid_integer(value)
    if field.type == "list":
        return _valid_list(value)
    if field.type == "enum":
        return _valid_enum(value, field.options)
    return _valid_text(value)


def validate_fields(descriptor: DocumentTypeDescriptor, raw: object) -> dict[str, Any]:
    """Validate each field independently; drop any that fail rather than
    rejecting the whole extraction over one bad value."""
    fields = raw if isinstance(raw, dict) else {}
    result: dict[str, Any] = {}
    for field in descriptor.fields:
        validated = _validate_one(field, fields.get(field.id))
        if validated is not None:
            result[field.id] = validated
    return result


def merge_fields(
    descriptor: DocumentTypeDescriptor, current: dict[str, Any], extracted: dict[str, Any]
) -> dict[str, Any]:
    """Merge newly extracted fields onto the accumulated known fields.

    Party sub-objects merge key-by-key; every other field is replaced
    wholesale when present in `extracted`.
    """
    party_field_ids = {f.id for f in descriptor.fields if f.type == "party"}
    merged = dict(current)
    for key, value in extracted.items():
        if key in party_field_ids and key in merged and isinstance(merged[key], dict):
            merged[key] = {**merged[key], **value}
        else:
            merged[key] = value
    return merged


def missing_required_fields(descriptor: DocumentTypeDescriptor, fields: dict[str, Any]) -> list[str]:
    return [f.label for f in descriptor.fields if f.required and not fields.get(f.id)]


# --- prompt generation -------------------------------------------------------


def _field_line(field: FieldSpec) -> str:
    parts = [f"- {field.id} ({field.label})"]
    if field.type == "enum" and field.options:
        parts.append(f": one of {', '.join(field.options)}")
    elif field.type == "party":
        parts.append(": an organization with companyName, signerName, signerTitle, noticeAddress")
    elif field.type == "list":
        parts.append(": a short list of items")
    elif field.type == "date":
        parts.append(": an ISO date YYYY-MM-DD")
    elif field.type == "integer":
        parts.append(": a whole number")
    if field.promptHint:
        parts.append(f". {field.promptHint}")
    return "".join(parts)


CLASSIFICATION_PROMPT_TEMPLATE = """You are helping a user figure out which legal document they need, \
then draft it through natural conversation.

Supported document types (id: name):
{catalog}

Instructions:
1. Read the user's latest message and any prior conversation to infer which supported document \
type they want. Only set "documentType" once you are reasonably confident - use the exact id \
from the list above.
2. If the user describes something not in the list above, do NOT set "documentType". Instead, \
explain in "reply" that we can't generate that document, and suggest the closest supported type \
by name.
3. If it's genuinely ambiguous which supported type they want, ask a short clarifying question in \
"reply" and leave "documentType" unset.
4. Write a short, friendly "reply" (2-4 sentences).

Reply with ONLY a single JSON object of the exact shape {{"reply": string, "documentType": string \
or null}} - no markdown, no prose outside the JSON.
"""


FIELD_PROMPT_TEMPLATE = """You are helping a user fill in a {document_name} through natural \
conversation.

Fields to collect:
{field_lines}

Fields already known from this conversation (do not ask about these again unless the user \
changes them):
{known_fields_json}

Instructions:
1. Extract any of the above fields the user's latest message reveals, however partial. Only \
include a field if the user actually stated it - never guess or invent a value.
2. Write a short, friendly reply (2-4 sentences) acknowledging what you learned and asking \
about one or two still-missing fields. Do not interrogate with a full checklist.
3. If everything is known, tell the user the document is ready to preview and download.

Reply with ONLY a single JSON object of the exact shape {{"reply": string, "fields": object}} - \
no markdown, no prose outside the JSON. "fields" must only use the field ids listed above; omit \
any field you didn't just learn. Party fields are objects with companyName/signerName/\
signerTitle/noticeAddress.
"""


def build_classification_prompt() -> str:
    return CLASSIFICATION_PROMPT_TEMPLATE.format(catalog=catalog_summary())


def build_field_prompt(descriptor: DocumentTypeDescriptor, known_fields: dict[str, Any]) -> str:
    field_lines = "\n".join(_field_line(f) for f in descriptor.fields)
    return FIELD_PROMPT_TEMPLATE.format(
        document_name=descriptor.catalogNames[0],
        field_lines=field_lines,
        known_fields_json=json.dumps(known_fields),
    )
